name: Deploy Pages

on:
  push:
    branches:
      - main # 触发此操作的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # 如果有子模块的话

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0' # 指定Node版本
    # 使用 最新的 PNPM
    # 你也可以指定为具体的版本
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: latest
        # version: 9
        run_install: false

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: pnpm install # 确保使用锁定的依赖版本

    - name: Build VitePress site
      run: pnpm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist # 替换为实际输出目录