name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Check file existence and content
        run: |
          echo "Checking if file exists..."
          if [ -f "docs/document/overview/update-log.md" ]; then
            echo "File exists. Printing content:"
            cat docs/document/overview/update-log.md
          else
            echo "File does not exist!"
            exit 1
          fi

      - name: Build VitePress site
        run: pnpm run build
